---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meridian-db-creds
  namespace: meridian-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBdFPOCpd/gWnRxeMqGi+5QkVyq113RKQlalH40q4ebOSBi6Un8MO7iw7mPy9kFXX5p6aXPLIgrWNnhozxUx9db+YOhbnWbX2vRaht3/1y5HVWOyvy0qXnYhNVez4vOWDlYBPSdcP9sQd41U2J0xWQ1/Gyyipouvn/BzYz+p5XC1hR6d9mPg53G4YzcXBR09IhhpCQ/jJztTHeXlWvE0jmYcpfZi3hpzyGfSPZ56+OfDlbHsWBXHASAm3Ny8pNTQ7IyHyYWotZj91OGtrpYvYNIjSFkNwtiJCR7LoiMvgLFHGjBI/PNGT8Ml0qFuoWbcOIyyPZnjh1fK1uNaa2YrjH0iH8BrcjlItgS2sEagJQ4nOC0loioBqT98hOAyBbJp5FVXKxVl2SM+0EH4FMGaxnyaKUntAnPjRpod+vHUENinfcP8tkQLOgPrkiRyBX45pvd3ojyAAoemc4WcvoQwiCqPGPBhw+4XxqpELEt/T89lzFlL0+PAWTskfrhTi6y0rojvQ2rasjERAa9Ka6ArowKuH3SfeMIapvd2Rs7GTwst+AXQ6B9gvePc8zowHW0EKrqmQqB++8wvBgaERB6lw+R8brqvD1nAmMsjsETJz9uKebsxrW//VO4ptrcW3teNjKgfskE3S3K/N3Td4qrwwOuwdb1aW1jx6EiQGgAvcaw8OVR/Wgebj0UFYYdcHMx51PdFb6SDUCtj148FMcxGAuuNyjhVLNgM6531D4p5M7ClQ==
  template:
    metadata:
      name: meridian-db-creds
      namespace: meridian-prod
