---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: podinfo-creds
  namespace: default
spec:
  encryptedData:
    api-key: AgC1XWmn3qe4JfbHDHn5Gmj3xDXTzi3BMjJE8nVLfu4xNfHz+N3XK83d+sqpqCYZ9Xa2I/WuJizWpUMh8aHa2aR+cMgJi2CBp6kxhFqzrltgeEcs/6A+wuDCtZ6VWl59b1BSQntcQqMyUALVo+E70jfb8C94cQaYrH0Me8yKoKynOksjqcvlD4m2NgFx7i++VSlgIWf0fu36S2NsANRxSpRdj5O8cAGJ4wOD6NKKjx8LOHE0HAGrT1ZI7Cao9eSfc+LauWGNS5Hs+DrqFT1xrT9/484zGVli2/alV8nfegC3alWi29RNUqrwxfd37rzApJr82kgEyDrsIeCUs8g+eFqoEVeWo3Vq88brCmVbNYeK/WDk7eXM2sLG7YXKeQ6OE/PmgHACgbTM7X1SViMMn16a03z5fldtVSnb6YRiM/w1CszLKtfg0ycIGafAzJiibgPduuRNQvB71M+j1xtwe38LOT4Aeh/a886xMRtQAqvgZal4epYBkHW/Ag+e/w7rY7icececuiR3YcHPYqmGyA+4tDk9Lw7FsGqrjy1t4bVlylPgV/uzklQyTBhgom+Q0Ces91BNF0lfyoofrKkZOaCaIw/Nd/TMNLogEAAorcA36V5/uQ9ALUpex0GS05wqXcrRu9eJY/jxuqPDuAILALcNL5wefLVdfKCUx5vLM2e3S9qYkSGm8EC+stc21mEI8gfwmb51OTppyLXnvHgdWA==
  template:
    metadata:
      name: podinfo-creds
      namespace: default
