---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: podinfo-creds
  namespace: default
spec:
  encryptedData:
    api-key: AgA/NJ/LoC0FRWM5zDiDoh69TpCcvNlY52V7b8jOkvlDkjvw8tjoB7l7ETufnrQqj8rP3WiWWEhtYoEsTPnjQgsb/4zluG5I0Hrz1RJg3j8+tgJatIcL1aRNmTJ9mtDR1sL1IhkxKqMy7uqXx9IDsbNZm/9dBJYiMBYsBNLfmTCDifTBqxqnpAcfAb326QAkS9LNqpzO3wdZhArBD52WfMlJyPSS6NQqa6+a5gYA98FMAjQJ+wDvDF7dK50m9LlkXgrJAcLfUcfK+KGMpAYOMvEd7Yo2PVY/Whqikq7Q+nDdQd4EnyafdlZ86csJx28My9l4Devt/eGOKzmo59GASanySx3iYYxdE3ndcyFeA8e+n+ITL4eBJC3dymdOThUH8IuOI/pIrfmabYNB+Hgect0ucSFauSxkQBeQ2g8TSXj9en7WmDBK08wmPY748o0WVRMvEIV4gYJnIFSwRq/a7BK7YtwUI/PtWDV+uuyYahGWsvBfT6E8n9jBR7pSwl85naoBXmnY/x1/DPIpyv0SxB3D9foP39hWZ4b6ErKPHrMrCvb07vslr9eUc7AXlbOi2PvybYJvero9j8ki6yK9J3haEkLvWwKlf6/7OvM8zZRnVhNJM0A6wLqf3p+Cym0fv7pUISYhXNkMvwieG481rmpcJyYXh+fOQufVn+FDAjFC15gItfoM6tnUEpaJz0qIIWyRURMVjl9gdQW2iOJTCQ==
  template:
    metadata:
      name: podinfo-creds
      namespace: default
